// source: src/redvox-api-1000.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.SingleChannel');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.SummaryStatistics');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SingleChannel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SingleChannel.repeatedFields_, null);
};
goog.inherits(proto.SingleChannel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SingleChannel.displayName = 'proto.SingleChannel';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SingleChannel.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SingleChannel.prototype.toObject = function(opt_includeInstance) {
  return proto.SingleChannel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SingleChannel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SingleChannel.toObject = function(includeInstance, msg) {
  var f, obj = {
    sensorDescription: jspb.Message.getFieldWithDefault(msg, 1, ""),
    meanSampleRateHz: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    sampleTsUsList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    samplesList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 4)) == null ? undefined : f,
    sampleRateStatistics: (f = msg.getSampleRateStatistics()) && proto.SummaryStatistics.toObject(includeInstance, f),
    sampleStatistics: (f = msg.getSampleStatistics()) && proto.SummaryStatistics.toObject(includeInstance, f),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SingleChannel}
 */
proto.SingleChannel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SingleChannel;
  return proto.SingleChannel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SingleChannel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SingleChannel}
 */
proto.SingleChannel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSensorDescription(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMeanSampleRateHz(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
      msg.setSampleTsUsList(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
      msg.setSamplesList(value);
      break;
    case 5:
      var value = new proto.SummaryStatistics;
      reader.readMessage(value,proto.SummaryStatistics.deserializeBinaryFromReader);
      msg.setSampleRateStatistics(value);
      break;
    case 6:
      var value = new proto.SummaryStatistics;
      reader.readMessage(value,proto.SummaryStatistics.deserializeBinaryFromReader);
      msg.setSampleStatistics(value);
      break;
    case 7:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SingleChannel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SingleChannel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SingleChannel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SingleChannel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSensorDescription();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMeanSampleRateHz();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getSampleTsUsList();
  if (f.length > 0) {
    writer.writePackedDouble(
      3,
      f
    );
  }
  f = message.getSamplesList();
  if (f.length > 0) {
    writer.writePackedDouble(
      4,
      f
    );
  }
  f = message.getSampleRateStatistics();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.SummaryStatistics.serializeBinaryToWriter
    );
  }
  f = message.getSampleStatistics();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.SummaryStatistics.serializeBinaryToWriter
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string sensor_description = 1;
 * @return {string}
 */
proto.SingleChannel.prototype.getSensorDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.setSensorDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double mean_sample_rate_hz = 2;
 * @return {number}
 */
proto.SingleChannel.prototype.getMeanSampleRateHz = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.setMeanSampleRateHz = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * repeated double sample_ts_us = 3;
 * @return {!Array<number>}
 */
proto.SingleChannel.prototype.getSampleTsUsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.setSampleTsUsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.addSampleTsUs = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.clearSampleTsUsList = function() {
  return this.setSampleTsUsList([]);
};


/**
 * repeated double samples = 4;
 * @return {!Array<number>}
 */
proto.SingleChannel.prototype.getSamplesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.setSamplesList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.addSamples = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.clearSamplesList = function() {
  return this.setSamplesList([]);
};


/**
 * optional SummaryStatistics sample_rate_statistics = 5;
 * @return {?proto.SummaryStatistics}
 */
proto.SingleChannel.prototype.getSampleRateStatistics = function() {
  return /** @type{?proto.SummaryStatistics} */ (
    jspb.Message.getWrapperField(this, proto.SummaryStatistics, 5));
};


/**
 * @param {?proto.SummaryStatistics|undefined} value
 * @return {!proto.SingleChannel} returns this
*/
proto.SingleChannel.prototype.setSampleRateStatistics = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.clearSampleRateStatistics = function() {
  return this.setSampleRateStatistics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SingleChannel.prototype.hasSampleRateStatistics = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional SummaryStatistics sample_statistics = 6;
 * @return {?proto.SummaryStatistics}
 */
proto.SingleChannel.prototype.getSampleStatistics = function() {
  return /** @type{?proto.SummaryStatistics} */ (
    jspb.Message.getWrapperField(this, proto.SummaryStatistics, 6));
};


/**
 * @param {?proto.SummaryStatistics|undefined} value
 * @return {!proto.SingleChannel} returns this
*/
proto.SingleChannel.prototype.setSampleStatistics = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.clearSampleStatistics = function() {
  return this.setSampleStatistics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.SingleChannel.prototype.hasSampleStatistics = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * map<string, string> metadata = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.SingleChannel.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.SingleChannel} returns this
 */
proto.SingleChannel.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};


